In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/var/folders/1q/ttq7y9792hl1j72br9_w4vzw0000gn/T/ipykernel_21456/555797462.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [7]:
encodings = ['utf-8', 'latin1', 'iso-8859-1', 'utf-16']

for encoding in encodings:
    try:
        df = pd.read_csv("./dataset/intercropping/data1.csv", encoding=encoding)
        # Jika pembacaan berhasil, keluar dari loop
        break
    except UnicodeDecodeError:
        print(f"Gagal membaca dengan encoding {encoding}. Mencoba encoding berikutnya...")

Gagal membaca dengan encoding utf-8. Mencoba encoding berikutnya...

In [8]:
display(df)

,author,year,journal,doi,location,type,cover,zone,map,map_note,...,avg_mbc_ctrl,stddev_mbc_ctrl,avg_mbc_trt,stddev_mbc_trt,lnrr_eea,var_lnrr_eea,lnrr_mbc,var_lnrr_mbc,assay_method,assay_soil
0,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.11,0.00,,,Guan,Fresh
1,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.07,0.01,,,Guan,Fresh
2,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.32,0.01,,,Guan,Fresh
3,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.03,0.01,,,Guan,Fresh
4,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.17,0.00,,,PNP,Fresh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,Xianchen et al.,2020,Journal of the Science of Food and Agriculture,10.1002/jsfa.10580,China,Field,Field,Temperate,NaN,NaN,...,NaN,NaN,NaN,NaN,0.38,0.02,,,Guan,Fresh
965,Xianchen et al.,2020,Journal of the Science of Food and Agriculture,10.1002/jsfa.10580,China,Field,Field,Temperate,NaN,NaN,...,NaN,NaN,NaN,NaN,0.30,0.02,,,KMnO4,Fresh
966,Rigal et al.,2020,Plant and Soil,10.1007/s11104-019-04004-1,China,Field,Field,Temperate,1400.0,NaN,...,34.73,15.49,39.58,10.82,0.03,0.01,0.13,0.02,4NN,NaN
967,Rigal et al.,2020,Plant and Soil,10.1007/s11104-019-04004-1,China,Field,Field,Temperate,1400.0,NaN,...,34.73,15.49,39.58,10.82,0.03,0.02,0.13,0.02,PNG,NaN
968,Rigal et al.,2020,Plant and Soil,10.1007/s11104-019-04004-1,China,Field,Field,Temperate,1400.0,NaN,...,34.73,15.49,39.58,10.82,0.11,0.01,0.13,0.02,PNP,NaN

In [10]:
display(df.describe())

,year,map,mat,ph,sand,silt,clay,tot_n,av_n,tot_p,...,avg_eea_ctrl,stddev_eea_ctrl,avg_eea_trt,stddev_avg_trt,avg_mbc_ctrl,stddev_mbc_ctrl,avg_mbc_trt,stddev_mbc_trt,lnrr_eea,var_lnrr_eea
count,969.000000,478.000000,404.000000,882.000000,557.000000,557.000000,592.000000,555.000000,604.000000,400.000000,...,969.000000,969.000000,969.000000,969.000000,275.000000,217.000000,275.000000,217.000000,969.000000,969.000000
mean,2015.138287,1002.556904,18.605693,6.541406,47.599677,30.278905,22.579780,1.394523,84.714272,0.740675,...,188.268359,19.143767,207.723818,19.545377,443.096109,78.584147,593.510182,70.725023,0.132848,0.023973
std,4.290999,544.038987,7.731065,1.361543,21.988893,15.740157,14.491243,1.652675,72.866589,0.558457,...,652.085397,99.471074,783.094303,83.726155,1681.617550,189.581870,2141.658641,177.617752,0.356921,0.107579
min,1998.000000,150.000000,5.500000,3.800000,5.600000,1.000000,4.000000,0.010000,0.120000,0.010000,...,0.020000,0.000000,0.050000,0.000000,1.180000,0.180000,1.020000,0.180000,-1.500000,0.000000
25%,2012.000000,468.000000,12.500000,5.360000,29.000000,17.900000,12.000000,0.920000,39.690000,0.380000,...,2.120000,0.210000,2.450000,0.220000,3.680000,0.680000,4.500000,0.680000,-0.030000,0.000000
50%,2016.000000,1193.500000,20.000000,6.300000,51.000000,32.400000,21.000000,1.200000,73.000000,0.680000,...,13.000000,1.290000,15.510000,1.450000,79.920000,5.890000,93.230000,3.080000,0.100000,0.010000
75%,2019.000000,1388.000000,25.000000,7.800000,57.000000,43.000000,25.000000,1.450000,113.200000,1.100000,...,61.900000,6.790000,74.300000,7.270000,225.790000,21.710000,217.000000,46.350000,0.280000,0.010000
max,2021.000000,2000.000000,29.000000,8.790000,90.000000,67.000000,70.000000,15.900000,539.400000,4.360000,...,6713.000000,2135.620000,13495.000000,928.590000,10004.000000,888.000000,12748.000000,888.000000,2.250000,2.110000

In [13]:
print(df.isnull().sum())
print("banyak data : ",len(df))

author               0
year                 0
journal              0
doi                  0
location             0
type                10
cover               10
zone               351
map                491
map_note           846
mat                565
ph                  87
sand               412
silt               412
clay               377
texture_note       753
tot_n              414
av_n               365
tot_p              569
av_p               155
som                372
soc                194
soc_note           400
n_fert_class       387
n_fert_amt         406
p_fert_amt         488
irrigated          734
duration            84
sample               8
depth              537
main                 0
main_cat             0
inter                0
inter_cat            0
n_ctrl               0
n_trt                0
ler                835
yield_rr           649
yield_lnrr         649
yield_ler          581
enz                  0
enz_ec              30
enz_type             0
avg_eea_ctrl         0
stddev_eea_ctrl      0
avg_eea_trt          0
stddev_avg_trt       0
stddev_note        794
avg_mbc_ctrl       694
stddev_mbc_ctrl    752
avg_mbc_trt        694
stddev_mbc_trt     752
lnrr_eea             0
var_lnrr_eea         0
lnrr_mbc             0
var_lnrr_mbc         0
assay_method       128
assay_soil         232
dtype: int64
banyak data :  969

In [15]:
display(df.columns)

Index(['author', 'year', 'journal', 'doi', 'location', 'type', 'cover', 'zone',
       'map', 'map_note', 'mat', 'ph', 'sand', 'silt', 'clay', 'texture_note',
       'tot_n', 'av_n', 'tot_p', 'av_p', 'som', 'soc', 'soc_note',
       'n_fert_class', 'n_fert_amt', 'p_fert_amt', 'irrigated', 'duration',
       'sample', 'depth', 'main', 'main_cat', 'inter', 'inter_cat', 'n_ctrl',
       'n_trt', 'ler', 'yield_rr', 'yield_lnrr', 'yield_ler', 'enz', 'enz_ec',
       'enz_type', 'avg_eea_ctrl', 'stddev_eea_ctrl', 'avg_eea_trt',
       'stddev_avg_trt', 'stddev_note', 'avg_mbc_ctrl', 'stddev_mbc_ctrl',
       'avg_mbc_trt', 'stddev_mbc_trt', 'lnrr_eea', 'var_lnrr_eea', 'lnrr_mbc',
       'var_lnrr_mbc', 'assay_method', 'assay_soil'],
      dtype='object')

In [16]:
pd.set_option('display.max_columns', None)

In [17]:
display(df.head())

,author,year,journal,doi,location,type,cover,zone,map,map_note,mat,ph,sand,silt,clay,texture_note,tot_n,av_n,tot_p,av_p,som,soc,soc_note,n_fert_class,n_fert_amt,p_fert_amt,irrigated,duration,sample,depth,main,main_cat,inter,inter_cat,n_ctrl,n_trt,ler,yield_rr,yield_lnrr,yield_ler,enz,enz_ec,enz_type,avg_eea_ctrl,stddev_eea_ctrl,avg_eea_trt,stddev_avg_trt,stddev_note,avg_mbc_ctrl,stddev_mbc_ctrl,avg_mbc_trt,stddev_mbc_trt,lnrr_eea,var_lnrr_eea,lnrr_mbc,var_lnrr_mbc,assay_method,assay_soil
0,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,29.0,6.2,20.0,43.0,36.0,NaN,1.2,40.6,0.25,12.6,NaN,9.7,NaN,Medium,200.0,52.0,NaN,2.0,Rhizosphere,NaN,Peanut,Legume,Maize,Grass,3,3,1.07,0.90,-0.11,1.07,Urease,3.5.1.5,Nitrogen,6.65,0.35,7.43,0.32,NaN,NaN,NaN,NaN,NaN,0.11,0.00,,,Guan,Fresh
1,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,29.0,6.2,20.0,43.0,36.0,NaN,1.2,40.6,0.25,12.6,NaN,9.7,NaN,Medium,200.0,52.0,NaN,2.0,Rhizosphere,NaN,Maize,Grass,Peanut,Legume,3,3,1.07,1.33,0.29,1.07,Urease,3.5.1.5,Nitrogen,6.92,0.79,7.43,0.32,NaN,NaN,NaN,NaN,NaN,0.07,0.01,,,Guan,Fresh
2,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,29.0,6.2,20.0,43.0,36.0,NaN,1.2,40.6,0.25,12.6,NaN,9.7,NaN,Medium,200.0,52.0,NaN,2.0,Rhizosphere,NaN,Peanut,Legume,Maize,Grass,3,3,1.07,0.90,-0.11,1.07,Invertase,3.2.1.26,Carbon,44.67,3.52,61.46,7.50,NaN,NaN,NaN,NaN,NaN,0.32,0.01,,,Guan,Fresh
3,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,29.0,6.2,20.0,43.0,36.0,NaN,1.2,40.6,0.25,12.6,NaN,9.7,NaN,Medium,200.0,52.0,NaN,2.0,Rhizosphere,NaN,Maize,Grass,Peanut,Legume,3,3,1.07,1.33,0.29,1.07,Invertase,3.2.1.26,Carbon,59.42,5.86,61.46,7.50,NaN,NaN,NaN,NaN,NaN,0.03,0.01,,,Guan,Fresh
4,Chen et al,2018,Applied Soil Ecology,10.1016/j.apsoil.2017.11.010,China,Pot,Covered,NaN,NaN,NaN,29.0,6.2,20.0,43.0,36.0,NaN,1.2,40.6,0.25,12.6,NaN,9.7,NaN,Medium,200.0,52.0,NaN,2.0,Rhizosphere,NaN,Peanut,Legume,Maize,Grass,3,3,1.07,0.90,-0.11,1.07,Acid phosphatase,3.1.3.2,Phosphorous,312.01,18.75,369.09,10.23,NaN,NaN,NaN,NaN,NaN,0.17,0.00,,,PNP,Fresh

In [27]:
print(df["location"].unique())

['China' 'Senegal' 'India' 'Brazil' 'South Africa' 'Turkey' 'Pakistan'
 'Brazi' 'Malawi' 'Egypt' 'Morocco' 'Canada' 'Kenya' 'Chile' 'Italy' 'USA']

In [19]:
print(df["main"].unique())

['Peanut' 'Maize' 'Sugarcane' 'Soybean' 'Mulberry' 'Pepper' 'Cucumber'
 'Alfalfa' 'Wild Rye' 'Shrub' 'Millet' 'Apple' 'Potato' 'Tea' 'Garlic'
 'Mango' 'Wheat/Maize Avg' 'Faba Bean/Maize Avg' 'Wheat' 'Faba Bean'
 'Baby corn' 'Chickpea' 'Lentil' 'Pea ' 'Maize/Chickpea avg'
 'Maize/Faba bean avg' 'Maize/Soybean avg' 'Maize/Turnip avg' 'Eggplant'
 'Cotton' 'Jatropha' 'Tomato' 'Pear' 'Coffee' 'Orange' 'Acacia (legume)'
 'Cowpea' 'Watermelon' 'Eucalyptus' 'Chinese fir' 'Wheat/Cowpea rotation'
 'Capsicum' 'Banana' 'Coconut' 'Sorghum' 'Barley' 'Pumpkin' 'Celery'
 'Sedum' 'Kangkong' 'Wheat (geno1)' 'Wheat (geno2)' 'Wheat (geno3)'
 'Wheat (geno4)' 'Plathymenia' 'Pidgeonpea' 'Grape (Thompson)'
 'Grape (Flame)' 'Forage grass' 'Forage grass (Tamani)'
 'Forage grass (Piata)' 'Camellia' 'Rubber' 'Olive' 'Ryegrass' 'Kiwifruit'
 'Guinea grass (BG1)' 'Guinea grass (BG2)' 'Acacia' 'Faba bean (Ka)'
 'Faba bean (Al)' 'Soybean (S1)' 'Soybean (S2)' 'Soybean (S3)' 'Rapeseed'
 'Chinese milk vetch' 'Calla lily' 'Buffelgrass' 'Garlic chives'
 'Nightshade' 'Grape' 'Dolichos' 'Lima bean' 'Lupin' 'Cassava' 'Amaranth'
 'Patchouli' 'Chinese cabbage' 'Spring cucumber' 'Autumn cucumber'
 'Faba bean' 'Triticale' 'Prairie grass' 'Rice' 'Thalia dealbata']

In [22]:
print(df["zone"].unique())

[nan 'Tropical' 'Temperate']

In [23]:
print((df["zone"] == "Tropical").sum())

230

In [24]:
print((df["zone"] == "Temperate").sum())

388

In [28]:
print(df["type"].unique())

['Pot' 'Field' 'Tunnel' 'Greenhouse plots' nan]

In [29]:
print(df['type'].value_counts())

type
Field               615
Pot                 222
Tunnel               98
Greenhouse plots     24
Name: count, dtype: int64

In [31]:
print(df["main"].value_counts())

main
Maize                 93
Cucumber              74
Peanut                68
Coffee                45
Sugarcane             37
                      ..
Guinea grass (BG2)     1
Guinea grass (BG1)     1
Wheat (geno4)          1
Plathymenia            1
Wheat (geno3)          1
Name: count, Length: 95, dtype: int64